name: indexpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - jupyter #for intellij jupyter only
  - jupyterlab #for examples only
  - sentence-transformers>=2.5.1
  - pip:
      - pycomfort>=0.0.15
      - pynction
      - polars>=0.20.14
      - beartype
      - click
      - twine
      - tiktoken
      - openai
      - chromadb>=0.4.24
      - qdrant-client>=1.8.0
      - datasets
      - fastembed>=0.2.2
      - hybrid_search>=0.0.12
