name: indexpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - cudatoolkit=11.6
  - pytorch<=1.13
  - sentence-transformers
  - jupyter #for intellij jupyter only
  - jupyterlab #for examples only
  - pip:
      - pynction
      - polars>=0.19.11
      - beartype
      - click
      - twine
      - tiktoken
      - langchain>=0.1.0
      - langchain-community>=0.0.11
      - openai
      - chromadb>=0.4.15
      - qdrant-client>=1.7.0
      - datasets
      - qdrant-client[fastembed]
      - hybrid_search>=0.0.7
