name: indexpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - jupyter #for intellij jupyter only
  - jupyterlab #for examples only
  - sentence-transformers
  - pip:
      - pycomfort>=0.0.15
      - pynction
      - polars>=0.19.11
      - beartype
      - click
      - twine
      - tiktoken
      - openai
      - chromadb>=0.4.15
      - qdrant-client>=1.7.3
      - datasets
      - qdrant-client[fastembed]
      - hybrid_search>=0.0.9
