name: indexpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - jupyter #for intellij jupyter only
  - jupyterlab #for examples only
  - pip:
      - pycomfort>=0.0.13
      - pynction
      - polars>=0.18.11
      - click
      - twine
      - tiktoken
      - openai
      - chromadb
      - langchain
      - qdrant-client
      - sentence_transformers
      - datasets