name: indexpaper
channels:
  - conda-forge
  - bioconda
  - pytorch
  - plotly
  - defaults
dependencies:
  - python=3.10
  - setuptools
  - pytorch
  - jupyter #for intellij jupyter only
  - jupyterlab #for examples only
  - pip:
      - pycomfort>=0.0.14
      - pynction
      - polars>=0.19.9
      - beartype
      - click
      - twine
      - tiktoken
      - openai
      - chromadb>=0.4.14
      - langchain>=0.0.320
      - qdrant-client>=1.6.1
      - sentence_transformers
      - datasets
